# -*- coding: utf-8 -*-
"""RMS_ZCR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Uosuca_Z5jXtcJVNeCBMn7qO2tqJ7aZ

Nesse script fiz alguns testes para achar a RMS e a ZCR de um sinal sonoro
"""

#bibliotecas
import matplotlib.pyplot as plt
import numpy as np
import librosa
import librosa.display
import IPython.display as ipd

#Load do sinal sonoro
guitar, _ = librosa.load('/content/luthier_pick_nonoise_mono_body.flac')

FRAME_LENGTH = 1024
HOP_LENGTH = 512
#RMS USING LIBROSA
rms_guitar = librosa.feature.rms(y=guitar, frame_length=FRAME_LENGTH, hop_length=HOP_LENGTH)[0]

frames = range(0, rms_guitar.size)
t = librosa.frames_to_time(frames)

plt.figure(figsize=(15, 5))
librosa.display.waveshow(guitar, sr=22050)
plt.plot(t,rms_guitar, color='r')
plt.show()

plt.figure(figsize=(15, 5))
plt.plot(t,rms_guitar, color='r')
plt.show()

#Rms através de uma função com numpy
def rms(signal, frame_size, hop_length):
    rms = []

    for i in range(0, len(signal), hop_length):
      current_frame_rms = np.sqrt(np.sum(signal[i:i+frame_size]**2)/frame_size)
      rms.append(current_frame_rms)

    return rms

rms_teste = rms(guitar, FRAME_LENGTH, HOP_LENGTH)

print(rms_teste)

frames = range(0, rms_guitar.size)
t = librosa.frames_to_time(frames)

plt.figure(figsize=(15, 5))
librosa.display.waveshow(guitar, sr=22050)
plt.plot(t,rms_teste, color='r')
plt.show()

# Zero_Crossing_Rate Using Librosa

zcr_guitar = librosa.feature.zero_crossing_rate(y=guitar, frame_length=FRAME_LENGTH, hop_length=HOP_LENGTH)[0]

plt.figure(figsize=(15, 5))
plt.plot(t,zcr_guitar * FRAME_LENGTH, color='r')
plt.ylim(0,100)
plt.show()